//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 Tencent.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by trpc-go/trpc-go-cmdline v2.0.17. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	"context"
	"errors"
	"fmt"
	reflect "reflect"

	"trpc.group/trpc-go/trpc-codec/grpc"
	common "trpc.group/trpc-go/trpc-codec/grpc/testdata/protocols/common"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	"trpc.group/trpc-go/trpc-go/filter"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// GreeterService defines service
type GreeterService interface {
	Hello(ctx context.Context, req *common.HelloReq) (*common.HelloRsp, error)
}

func GreeterService_Hello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &common.HelloReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GreeterService).Hello(ctx, reqbody.(*common.HelloReq))
	}

	// get req from ctx
	grpcData := ctx.Value(grpc.ContextKeyHeader).(*grpc.Header)
	req = grpcData.Req.(*common.HelloReq)

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	// set rsp to ctx, and set rsp empty
	grpcData.Rsp = rsp
	rsp = &common.HelloRsp{}
	return rsp, nil
}

// GreeterServer_ServiceDesc descriptor for server.RegisterService
var GreeterServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.app.server.Greeter",
	HandlerType: ((*GreeterService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.app.server.Greeter/Hello",
			Func: GreeterService_Hello_Handler,
		},
	},
}

// RegisterGreeterService register service
func RegisterGreeterService(s server.Service, svr GreeterService) {
	if err := s.Register(&GreeterServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Greeter register error:%v", err))
	}
	// register service to grpc
	if err := grpc.Register(GreeterServer_ServiceDesc.ServiceName,
		"greeter.proto",
		[]grpc.RegisterMethodsInfo{
			{
				Method: server.Method{
					Name: "Hello",
					Func: GreeterService_Hello_Handler,
				},
				ReqType: reflect.TypeOf(common.HelloReq{}),
				RspType: reflect.TypeOf(common.HelloRsp{}),
			},
		}); err != nil {
		panic(fmt.Sprintf("grpc register Greeter error:%v", err))
	}
	if err := grpc.RegisterStream(GreeterServer_ServiceDesc.ServiceName,
		"greeter.proto",
		GreeterServer_ServiceDesc.Streams,
		svr, (*GreeterService)(nil)); err != nil {
		panic(fmt.Sprintf("grpc register Greeter streams error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedGreeter struct{}

func (s *UnimplementedGreeter) Hello(ctx context.Context, req *common.HelloReq) (*common.HelloRsp, error) {
	return nil, errors.New("rpc Hello of service Greeter is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// GreeterClientProxy defines service client proxy
type GreeterClientProxy interface {
	Hello(ctx context.Context, req *common.HelloReq, opts ...client.Option) (rsp *common.HelloRsp, err error)
}

type GreeterClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewGreeterClientProxy = func(opts ...client.Option) GreeterClientProxy {
	return &GreeterClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *GreeterClientProxyImpl) Hello(ctx context.Context, req *common.HelloReq, opts ...client.Option) (*common.HelloRsp, error) {
	// set req to ctx
	h := ctx.Value(grpc.ContextKeyHeader)
	var header *grpc.Header
	if h == nil {
		header = &grpc.Header{}
		ctx = context.WithValue(ctx, grpc.ContextKeyHeader, header)
	} else {
		var ok bool
		header, ok = h.(*grpc.Header)
		if !ok {
			return nil, errors.New(fmt.Sprintf("grpc header in context cannot be transfered to grpc.Header"))
		}
	}
	header.Req = req
	header.Rsp = &common.HelloRsp{}
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.app.server.Greeter/Hello")
	msg.WithCalleeServiceName(GreeterServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("app")
	msg.WithCalleeServer("server")
	msg.WithCalleeService("Greeter")
	msg.WithCalleeMethod("Hello")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &common.HelloRsp{}
	callopts = append(callopts, client.WithProtocol("grpc"))
	callopts = append(callopts, client.WithFilter(func(ctx context.Context, req1, rsp1 interface{}, next filter.ClientHandleFunc) error {
		err := next(ctx, req1, rsp1)
		header := ctx.Value(grpc.ContextKeyHeader).(*grpc.Header)
		*rsp = *header.Rsp.(*common.HelloRsp)
		return err
	}))
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
